In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import os
print("notebook is running from:", os.getcwd())
print("contents:", os.listdir())

notebook is running from: c:\Users\Opeyemi\OneDrive - UNC Kenan-Flagler Business School\Desktop\Data Science\Ridewise-Project\notebook
contents: ['data cleaning.ipynb', 'EDA.ipynb']

In [4]:
files = {
    'sessions':   ('session_time',),
    'riders':     ('signup_date',),
    'drivers':    ('signup_date', 'last_active'),
    'trips':      ('pickup_time', 'dropoff_time'),
    'promotions': ('start_date', 'end_date'),
}
dfs = {}
for name, date_cols in files.items():
    dfs[name] = pd.read_csv(f'../ridewise project dataset/{name}.csv', parse_dates=list(date_cols))
    print(f'{name:10s}  {dfs[name].shape}')
    display(dfs[name].head())

sessions    (50000, 8)

,session_id,rider_id,session_time,time_on_app,pages_visited,converted,city,loyalty_status
0,S000000,R08605,2025-04-27 18:57:06+02:05,79,4,1,Cairo,Bronze
1,S000001,R08823,2025-04-27 07:32:22+02:27,101,3,0,Nairobi,Silver
2,S000002,R05342,2025-04-27 23:17:25+02:05,12,1,0,Cairo,Bronze
3,S000003,R05057,2025-04-27 14:40:25+00:14,19,1,0,Lagos,Silver
4,S000004,R09614,2025-04-27 08:31:22+00:14,4,1,0,Lagos,Bronze

riders      (10000, 8)

,user_id,signup_date,loyalty_status,age,city,avg_rating_given,churn_prob,referred_by
0,R00000,2025-01-24,Bronze,34.729629,Nairobi,5.0,0.142431,R00001
1,R00001,2024-09-09,Bronze,34.571020,Nairobi,4.7,0.674161,NaN
2,R00002,2024-09-07,Bronze,47.133960,Lagos,4.2,0.510379,NaN
3,R00003,2025-03-17,Bronze,41.658628,Nairobi,4.9,0.244779,NaN
4,R00004,2024-08-20,Silver,40.681709,Lagos,3.9,0.269960,R00002

drivers     (5000, 7)

,driver_id,rating,vehicle_type,signup_date,last_active,city,acceptance_rate
0,D00000,3.1,SUV,2025-01-20,2025-01-06 18:23:09.312275,Cairo,0.679555
1,D00001,5.0,Sedan,2023-03-27,2025-04-27 01:44:02.472554,Nairobi,0.548786
2,D00002,4.5,Motorcycle,2024-05-02,2025-03-07 19:24:46.367672,Nairobi,0.593724
3,D00003,5.0,Motorcycle,2023-04-16,2025-03-26 19:16:24.253793,Nairobi,0.990000
4,D00004,4.4,Motorcycle,2023-05-28,2025-04-08 18:54:44.649615,Lagos,0.519773

trips       (200000, 16)

,trip_id,user_id,driver_id,fare,surge_multiplier,tip,payment_type,pickup_time,dropoff_time,pickup_lat,pickup_lng,dropoff_lat,dropoff_lng,weather,city,loyalty_status
0,T000000,R05207,D00315,12.11,1.0,0.00,Card,2024-11-27 18:41:50+02:27,2024-11-27 19:33:50+02:27,-1.108123,36.912209,-1.068155,36.875377,Foggy,Nairobi,Bronze
1,T000001,R09453,D03717,8.73,1.0,0.02,Card,2024-10-28 23:13:48+00:14,2024-10-28 23:26:48+00:14,6.675266,3.515740,6.641734,3.525620,Sunny,Lagos,Gold
2,T000002,R00567,D02035,19.68,1.0,0.00,Card,2025-02-17 05:36:41+02:27,2025-02-17 05:52:41+02:27,-1.248589,37.010668,-1.273182,37.018586,Cloudy,Nairobi,Bronze
3,T000003,R09573,D02657,16.43,1.0,0.01,Mobile Money,2024-06-18 19:27:14+02:05,2024-06-18 19:32:14+02:05,29.819554,31.188780,29.837689,31.232978,Cloudy,Cairo,Bronze
4,T000004,R03446,D01026,8.70,1.0,1.06,Card,2024-10-05 09:58:16+02:27,2024-10-05 10:28:16+02:27,-1.676479,36.729219,-1.638395,36.694063,Sunny,Nairobi,Gold

promotions  (20, 11)

,promo_id,promo_name,promo_type,promo_value,start_date,end_date,target_segment,city_scope,ab_test_groups,test_allocation,success_metric
0,P000,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-25,All,Nairobi,['All'],[1.0],Usage Frequency
1,P001,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-22,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
2,P002,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-16,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
3,P003,Loyalty Bonus,points,100.0,2025-04-26,2025-05-04,Gold+,Nairobi,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
4,P004,Loyalty Bonus,points,100.0,2025-04-26,2025-05-15,Gold+,Nairobi,['All'],[1.0],Usage Frequency

In [5]:
print(dfs['sessions'].head().to_string())
dfs['sessions'].shape
dfs['sessions'].info()

  session_id rider_id               session_time  time_on_app  pages_visited  converted     city loyalty_status
0    S000000   R08605  2025-04-27 18:57:06+02:05           79              4          1    Cairo         Bronze
1    S000001   R08823  2025-04-27 07:32:22+02:27          101              3          0  Nairobi         Silver
2    S000002   R05342  2025-04-27 23:17:25+02:05           12              1          0    Cairo         Bronze
3    S000003   R05057  2025-04-27 14:40:25+00:14           19              1          0    Lagos         Silver
4    S000004   R09614  2025-04-27 08:31:22+00:14            4              1          0    Lagos         Bronze
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      50000 non-null  str
 1   rider_id        50000 non-null  str
 2   session_time    50000 non-null  str
 3   time_on_app     50000 non-null  int64
 4   pages_visited   50000 non-null  int64
 5   converted       50000 non-null  int64
 6   city            50000 non-null  str
 7   loyalty_status  50000 non-null  str
dtypes: int64(3), str(5)
memory usage: 3.1 MB

In [6]:
print(dfs['riders'].head())
dfs['riders'].shape
dfs['riders'].info()

  user_id signup_date loyalty_status        age     city  avg_rating_given  \
0  R00000  2025-01-24         Bronze  34.729629  Nairobi               5.0
1  R00001  2024-09-09         Bronze  34.571020  Nairobi               4.7
2  R00002  2024-09-07         Bronze  47.133960    Lagos               4.2
3  R00003  2025-03-17         Bronze  41.658628  Nairobi               4.9
4  R00004  2024-08-20         Silver  40.681709    Lagos               3.9

   churn_prob referred_by
0    0.142431      R00001
1    0.674161         NaN
2    0.510379         NaN
3    0.244779         NaN
4    0.269960      R00002
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10000 non-null  str
 1   signup_date       10000 non-null  datetime64[us]
 2   loyalty_status    10000 non-null  str
 3   age               10000 non-null  float64
 4   city              10000 non-null  str
 5   avg_rating_given  10000 non-null  float64
 6   churn_prob        10000 non-null  float64
 7   referred_by       3053 non-null   str
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB

In [7]:
print(dfs['trips'].head())
dfs['trips'].shape
dfs['trips'].info()

   trip_id user_id driver_id   fare  surge_multiplier   tip  payment_type  \
0  T000000  R05207    D00315  12.11               1.0  0.00          Card
1  T000001  R09453    D03717   8.73               1.0  0.02          Card
2  T000002  R00567    D02035  19.68               1.0  0.00          Card
3  T000003  R09573    D02657  16.43               1.0  0.01  Mobile Money
4  T000004  R03446    D01026   8.70               1.0  1.06          Card

                 pickup_time               dropoff_time  pickup_lat  \
0  2024-11-27 18:41:50+02:27  2024-11-27 19:33:50+02:27   -1.108123
1  2024-10-28 23:13:48+00:14  2024-10-28 23:26:48+00:14    6.675266
2  2025-02-17 05:36:41+02:27  2025-02-17 05:52:41+02:27   -1.248589
3  2024-06-18 19:27:14+02:05  2024-06-18 19:32:14+02:05   29.819554
4  2024-10-05 09:58:16+02:27  2024-10-05 10:28:16+02:27   -1.676479

   pickup_lng  dropoff_lat  dropoff_lng weather     city loyalty_status
0   36.912209    -1.068155    36.875377   Foggy  Nairobi         Bronze
1    3.515740     6.641734     3.525620   Sunny    Lagos           Gold
2   37.010668    -1.273182    37.018586  Cloudy  Nairobi         Bronze
3   31.188780    29.837689    31.232978  Cloudy    Cairo         Bronze
4   36.729219    -1.638395    36.694063   Sunny  Nairobi           Gold
<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   trip_id           200000 non-null  str
 1   user_id           200000 non-null  str
 2   driver_id         200000 non-null  str
 3   fare              200000 non-null  float64
 4   surge_multiplier  200000 non-null  float64
 5   tip               200000 non-null  float64
 6   payment_type      200000 non-null  str
 7   pickup_time       200000 non-null  str
 8   dropoff_time      200000 non-null  str
 9   pickup_lat        200000 non-null  float64
 10  pickup_lng        200000 non-null  float64
 11  dropoff_lat       200000 non-null  float64
 12  dropoff_lng       200000 non-null  float64
 13  weather           200000 non-null  str
 14  city              200000 non-null  str
 15  loyalty_status    200000 non-null  str
dtypes: float64(7), str(9)
memory usage: 24.4 MB

In [8]:
pd.set_option('display.max_columns', None)
print(dfs['promotions'].to_string())
dfs['promotions'].shape
dfs['promotions'].info(verbose=True, show_counts=True)

   promo_id           promo_name    promo_type  promo_value start_date   end_date target_segment  city_scope                         ab_test_groups  test_allocation   success_metric
0      P000       Peak Hour Pass  surge_waiver          1.0 2025-04-26 2025-05-25            All     Nairobi                                ['All']            [1.0]  Usage Frequency
1      P001       Peak Hour Pass  surge_waiver          1.0 2025-04-26 2025-05-22            All       Cairo  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]  Conversion Rate
2      P002       Peak Hour Pass  surge_waiver          1.0 2025-04-26 2025-05-16            All       Cairo  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]              ROI
3      P003        Loyalty Bonus        points        100.0 2025-04-26 2025-05-04          Gold+     Nairobi  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]  Conversion Rate
4      P004        Loyalty Bonus        points        100.0 2025-04-26 2025-05-15          Gold+     Nairobi                                ['All']            [1.0]  Usage Frequency
5      P005        Loyalty Bonus        points        100.0 2025-04-26 2025-05-16          Gold+     Nairobi                                ['All']            [1.0]  Usage Frequency
6      P006  First Ride Discount      discount          0.3 2025-04-26 2025-05-06            New       Lagos                                ['All']            [1.0]  Usage Frequency
7      P007  First Ride Discount      discount          0.3 2025-04-26 2025-05-26            New     Nairobi                                ['All']            [1.0]              ROI
8      P008     Referral Special        credit         15.0 2025-04-26 2025-05-03         Active  All-Cities                                ['All']            [1.0]  Usage Frequency
9      P009     Referral Special        credit         15.0 2025-04-26 2025-05-18         Active       Cairo  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]              ROI
10     P010  First Ride Discount      discount          0.3 2025-04-26 2025-05-05            New  All-Cities  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]  Conversion Rate
11     P011       Peak Hour Pass  surge_waiver          1.0 2025-04-26 2025-05-24            All     Nairobi  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]              ROI
12     P012        Loyalty Bonus        points        100.0 2025-04-26 2025-05-09          Gold+  All-Cities  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]              ROI
13     P013  First Ride Discount      discount          0.3 2025-04-26 2025-05-09            New  All-Cities                                ['All']            [1.0]              ROI
14     P014  First Ride Discount      discount          0.3 2025-04-26 2025-05-19            New       Lagos  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]              ROI
15     P015       Peak Hour Pass  surge_waiver          1.0 2025-04-26 2025-05-17            All  All-Cities  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]              ROI
16     P016        Loyalty Bonus        points        100.0 2025-04-26 2025-05-06          Gold+       Lagos                                ['All']            [1.0]  Usage Frequency
17     P017  First Ride Discount      discount          0.3 2025-04-26 2025-05-06            New       Lagos                                ['All']            [1.0]              ROI
18     P018  First Ride Discount      discount          0.3 2025-04-26 2025-05-13            New       Cairo  ['Control', 'Variant A', 'Variant B']  [0.3, 0.4, 0.3]              ROI
19     P019  First Ride Discount      discount          0.3 2025-04-26 2025-05-08            New       Lagos                                ['All']            [1.0]  Conversion Rate
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   promo_id         20 non-null     str
 1   promo_name       20 non-null     str
 2   promo_type       20 non-null     str
 3   promo_value      20 non-null     float64
 4   start_date       20 non-null     datetime64[us]
 5   end_date         20 non-null     datetime64[us]
 6   target_segment   20 non-null     str
 7   city_scope       20 non-null     str
 8   ab_test_groups   20 non-null     str
 9   test_allocation  20 non-null     str
 10  success_metric   20 non-null     str
dtypes: datetime64[us](2), float64(1), str(8)
memory usage: 1.8 KB

In [9]:
print(dfs['drivers'].head().to_string())
dfs['drivers'].shape
dfs['drivers'].info()

  driver_id  rating vehicle_type signup_date                last_active     city  acceptance_rate
0    D00000     3.1          SUV  2025-01-20 2025-01-06 18:23:09.312275    Cairo         0.679555
1    D00001     5.0        Sedan  2023-03-27 2025-04-27 01:44:02.472554  Nairobi         0.548786
2    D00002     4.5   Motorcycle  2024-05-02 2025-03-07 19:24:46.367672  Nairobi         0.593724
3    D00003     5.0   Motorcycle  2023-04-16 2025-03-26 19:16:24.253793  Nairobi         0.990000
4    D00004     4.4   Motorcycle  2023-05-28 2025-04-08 18:54:44.649615    Lagos         0.519773
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   driver_id        5000 non-null   str
 1   rating           5000 non-null   float64
 2   vehicle_type     5000 non-null   str
 3   signup_date      5000 non-null   datetime64[us]
 4   last_active      5000 non-null   datetime64[us]
 5   city             5000 non-null   str
 6   acceptance_rate  5000 non-null   float64
dtypes: datetime64[us](2), float64(2), str(3)
memory usage: 273.6 KB

###### Task 1
###### check the hypothesis that convertered riders are stored in trips dataset
###### check whether riders table contains information where session converted is 1

###### Classification problem
###### Engineer our target => We need to set a threshold to determin churn or not churn when churn is 1 and when it is 0

In [ ]:
###### basic data checks
# null values
# duplicates
# info()

###### simple table profiling
# describe()
# distributions
# outliers
# categories and cardinalities

###### next steps
# answer key questions from the data
# then move to modeling

In [15]:
for name, df in dfs.items():
    print(f"\n{name.upper()}")
    print("Null values:")
    print(df.isnull().sum())
    print("\nDuplicates:")
    print(df.duplicated().sum())
    print("\nInfo:")
    df.info()

SESSIONS
Null values:
session_id        0
rider_id          0
session_time      0
time_on_app       0
pages_visited     0
converted         0
city              0
loyalty_status    0
dtype: int64

Duplicates:
0

Info:
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      50000 non-null  str
 1   rider_id        50000 non-null  str
 2   session_time    50000 non-null  str
 3   time_on_app     50000 non-null  int64
 4   pages_visited   50000 non-null  int64
 5   converted       50000 non-null  int64
 6   city            50000 non-null  str
 7   loyalty_status  50000 non-null  str
dtypes: int64(3), str(5)
memory usage: 3.1 MB

RIDERS
Null values:
user_id                0
signup_date            0
loyalty_status         0
age                    0
city                   0
avg_rating_given       0
churn_prob             0
referred_by         6947
dtype: int64

Duplicates:
0

Info:
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10000 non-null  str
 1   signup_date       10000 non-null  datetime64[us]
 2   loyalty_status    10000 non-null  str
 3   age               10000 non-null  float64
 4   city              10000 non-null  str
 5   avg_rating_given  10000 non-null  float64
 6   churn_prob        10000 non-null  float64
 7   referred_by       3053 non-null   str
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB

DRIVERS
Null values:
driver_id          0
rating             0
vehicle_type       0
signup_date        0
last_active        0
city               0
acceptance_rate    0
dtype: int64

Duplicates:
0

Info:
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   driver_id        5000 non-null   str
 1   rating           5000 non-null   float64
 2   vehicle_type     5000 non-null   str
 3   signup_date      5000 non-null   datetime64[us]
 4   last_active      5000 non-null   datetime64[us]
 5   city             5000 non-null   str
 6   acceptance_rate  5000 non-null   float64
dtypes: datetime64[us](2), float64(2), str(3)
memory usage: 273.6 KB

TRIPS
Null values:
trip_id             0
user_id             0
driver_id           0
fare                0
surge_multiplier    0
tip                 0
payment_type        0
pickup_time         0
dropoff_time        0
pickup_lat          0
pickup_lng          0
dropoff_lat         0
dropoff_lng         0
weather             0
city                0
loyalty_status      0
dtype: int64

Duplicates:
0

Info:
<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   trip_id           200000 non-null  str
 1   user_id           200000 non-null  str
 2   driver_id         200000 non-null  str
 3   fare              200000 non-null  float64
 4   surge_multiplier  200000 non-null  float64
 5   tip               200000 non-null  float64
 6   payment_type      200000 non-null  str
 7   pickup_time       200000 non-null  str
 8   dropoff_time      200000 non-null  str
 9   pickup_lat        200000 non-null  float64
 10  pickup_lng        200000 non-null  float64
 11  dropoff_lat       200000 non-null  float64
 12  dropoff_lng       200000 non-null  float64
 13  weather           200000 non-null  str
 14  city              200000 non-null  str
 15  loyalty_status    200000 non-null  str
dtypes: float64(7), str(9)
memory usage: 24.4 MB

PROMOTIONS
Null values:
promo_id           0
promo_name         0
promo_type         0
promo_value        0
start_date         0
end_date           0
target_segment     0
city_scope         0
ab_test_groups     0
test_allocation    0
success_metric     0
dtype: int64

Duplicates:
0

Info:
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   promo_id         20 non-null     str
 1   promo_name       20 non-null     str
 2   promo_type       20 non-null     str
 3   promo_value      20 non-null     float64
 4   start_date       20 non-null     datetime64[us]
 5   end_date         20 non-null     datetime64[us]
 6   target_segment   20 non-null     str
 7   city_scope       20 non-null     str
 8   ab_test_groups   20 non-null     str
 9   test_allocation  20 non-null     str
 10  success_metric   20 non-null     str
dtypes: datetime64[us](2), float64(1), str(8)
memory usage: 1.8 KB